### PR TITLE
Add support for baking CRUD templates with Twig

### PR DESCRIPTION
**Pull request by HavokInspiration**
One thing I missed while using the plugin is the ability to use bake to generate basic CRUD action.
This PR adds the support for this feature.

To use it, the bake `theme` option has to be used. Let's say you have a TasksController, the following command can be used to generate basic CRUD : 

```bash
bin/cake bake twig_template Tasks all -t WyriHaximus/TwigView
```

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Awesome! Will go over the changes tomorrow, looks good at first skin though :+1:

**Comment by HavokInspiration** [comment]
The Travis build failure seems to be because of the bake version I required in the composer.json file which is not compatible with PHP 5.4.
The other failure is because of the lowest bake depency it can resolve which did not support the index column limit feature.
I'll take a look after lunch to see if I can downgrade it without losing everything.

**Comment by WyriHaximus** [comment]
> I'll take a look after lunch to see if I can downgrade it without losing everything.

Let me know if that is possible. If not, I wouldn't mind requiring PHP 5.5 and CakePHP 3.2 for TwigView 3.3 :).

**Comment by HavokInspiration** [comment]
I managed to have a build passing : I skippe a test if the `index-column` option is not available.

However, there is one important thing to know : I had to drop the composer.lock file. Since it locked the dependencies (and I updated it the lock file when I `composer install` the lib yesterday), it had too much high dependency for PHP 5.4. The problem with having the lock file is that the lib was only tested against CakePHP 3.0.0 (and everything was not really "dynamic"), even when not in the case of "lowest dependency".

Anyway, if you want to keep the lock file, I don't mind at all : I can restore it to its master state but we will indeed have to bump the requirement for 5.5 for this feature to be added.

**Comment by HavokInspiration** [comment]
I managed to have a build passing : I skipped a test if the `index-column` option is not available.

However, there is one important thing to know : I had to drop the composer.lock file. Since it locked the dependencies (and I updated it the lock file when I `composer install` the lib yesterday), it had too much high dependency for PHP 5.4. The problem with having the lock file is that the lib was only tested against CakePHP 3.0.0 (and everything was not really "dynamic"), even when not in the case of "lowest dependency".

Anyway, if you want to keep the lock file, I don't mind at all : I can restore it to its master state but we will indeed have to bump the requirement for 5.5 for this feature to be added.

Edit : Well, I can still restore it to its master state and had the lowest bake dependency possible, that should allow the build to pass. I can try that tonight if you'd prefer this solution.

**Comment by WyriHaximus** [comment]
Wouldn't mind bumping to 5.5. Do prefer keeping the lock file in because it allows testing against locked versions, lowest possible, and highest possible. As a result of that the latest tag has been tested against CakePHP [3.0](https://travis-ci.org/WyriHaximus/TwigView/jobs/146882290#L309), [3.1](https://travis-ci.org/WyriHaximus/TwigView/jobs/146882302#L295), and [3.2](https://travis-ci.org/WyriHaximus/TwigView/jobs/146882303#L300). The interesting thing there is that highest possible for PHP 5.4 tested against CakePHP 3.1, while the job for PHP 5.5 tested against CakePHP 3.2.

Not really a fan of skipping tests, if that means we're going to bump we're going to bump :smile: .

**Comment by HavokInspiration** [comment]
So I restored the composer.lock file, and bumped everything (PHP 5.5, Cake 3.2).
But I still had to skip the test that needs a specific version of bake because of the lowest dependency tests does not use that specific version.
It should be good now.

**Comment by WyriHaximus** [comment]
Interesting, bake [1.2.0](https://travis-ci.org/WyriHaximus/TwigView/jobs/147538665#L263) doesn't work but [1.2.7](https://travis-ci.org/WyriHaximus/TwigView/jobs/147538655#L308) does. Could you try to target bake at [`^1.2.2`](https://github.com/cakephp/bake/releases/tag/1.2.2), I have a feeling that will work?

**Comment by HavokInspiration** [comment]
Well, that is for sure, since the option was added with that release. I'll bump it.

**Comment by HavokInspiration** [comment]
Pushed. The build is almost done and all is green for now. I removed the skip.

**Comment by WyriHaximus** [comment]
Awesome :+1:, will have a look at the implementation tomorrow.

**Comment by HavokInspiration** [comment]
Any questions I can shed some light on with the PR ?
I'll happily answer them :)

**Comment by WyriHaximus** [comment]
Give me two hours :smile: .

**Comment by WyriHaximus** [comment]
Yup looks good, thanks for the PR and your tremendous amount of work on it, I'll tag it shortly :+1:

**Comment by WyriHaximus** [comment]
Tagged: https://github.com/WyriHaximus/TwigView/releases/tag/3.3.0

**Comment by HavokInspiration** [comment]
No problem, it was my pleasure :)

**Pull request merged**
