### PR TITLE
Add missing interfaces for loader

### PR DESCRIPTION
**Pull request by WyriHaximus**
Related https://github.com/cakephp/bake/issues/413

### CODE REVIEW

**Comment by dereuromark** [comment]
Any plans on moving up to date to current Twig (2.4.4+)? https://packagist.org/packages/twig/twig

**Comment by ionas** [comment]
Master is going against ^2.3 at least: https://github.com/WyriHaximus/TwigView/blob/master/composer.json#L28

**Comment by WyriHaximus** [comment]
@dereuromark as @ionas already mentions master is at nearly the latest. I haven't tagged master as `5.0.0` yet because I want(ed) to wait if and what kind of issues user run into now that `cakephp/bake` is using it. And it hasn't been a while up and until today that an issue came up. So I might just start porting the fixes to master, run some final tests before tagging `5.0.0` :smile: . Unless you or @ADmad has objections of things they like to see fixed in `4.x`?

**Comment by ADmad** [comment]
@WyriHaximus One issue is the plugin's master / 5.x  is PHP 7.0+ but we need bake to be PHP 5.6+ until Cake 4 is released.

**Comment by dereuromark** [comment]
Your plugin should support both major twig versions.
This way people already using 7.1+ can get the lstest version.
Others can stay on 5.6.

Is it difficult to shim to Provide both  inside same branch?

**Comment by ionas** [comment]
Twig ^2.0 requires PHP 7 so I am not sure what the request would be? As far as I understand TwigView 4.x will support Twig 1.x and thus PHP 5.6 and CakePHP 3.x where as TwigView 5.x supports CakePHP 4 / CakePHP 3.x on PHP7+?

**Comment by WyriHaximus** [comment]
I'll research the possibilities and get back with an overview. There are some possibilities we could consider.

**Pull request merged**
