### PR TITLE
Add filter for str_replace().

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Any reason you want to go `str_replace` over the native [`replace`](https://twig.symfony.com/doc/2.x/filters/replace.html)?

**Comment by ADmad** [comment]
Ignorance :P

**Comment by ADmad** [comment]
I am still new to twig :)

**Comment by WyriHaximus** [comment]
Fair enough, I've been there as well =D

**Comment by ADmad** [comment]
On a related note I need `strpos` too and pretty sure it's not available in twig itself.

It is available through filter provided by this plugin https://github.com/umpirsky/twig-php-function. I can include it in `cakephp/bake` but perhaps it would be better adding it to your plugin itself?

**Comment by ADmad** [comment]
`umpirsky/twig-php-function` is PHP 7.0+ so I guess can't include it in 4.x.

**Comment by WyriHaximus** [comment]
Ow that would be awesome 😁 ! Also v0.1 supports PHP 5.3 and up: https://github.com/umpirsky/twig-php-function/blob/v0.1/composer.json

**Pull request closed without merging**
