### PR TITLE
Add "config" function.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
The test failures seem unrelated to this change.

**Comment by inoas** [comment]
Can you also add `configOrFail()`? Or link `config()` to `readOrFail()`?

**Comment by ADmad** [comment]
I don't see any need for throwing exceptions in templates.

**Comment by inoas** [comment]
Well I don't see the need for calling values that may or may not exist.
Summa summarum, add both, people have the choice?

**Comment by ADmad** [comment]
I am not gonna make a PR for something I technically disagree with. Templates have should be dumb, they have no business throwing exceptions. I'll leave it to @WyriHaximus whether to accept or reject the PR in it's current form.

**Comment by WyriHaximus** [comment]
@ADmad yeah those are unrelated

**Comment by WyriHaximus** [comment]
@inoas I agree with @ADmad here, templates should know and have access as little as possible, preferable non from outside their score. So this PR technically already breaks that because you can access all config settings from here. But I'm still merging it because I see use cases.

I'de rather like to see a `hasConfig()` over a `configOrFail()` tbh

**Comment by inoas** [comment]
Thinking about this again, it should not be merged at all / enabled by default as it makes it easy to leak system context infos into templates - like say database credentials.

**Comment by ADmad** [comment]
DB credentials are **consumed** in bootstrap itself. https://github.com/cakephp/app/blob/master/config/bootstrap.php#L146

**Comment by inoas** [comment]
The security hash is not consumed is it?

**Comment by ADmad** [comment]
See 4 lines down to the one I have linked and you have your answer.

Anyway no config value is gonna magically show up in your template unless you actually read it, so it's a non issue.

**Comment by inoas** [comment]
Long short: My point of view: Either you separate concerns, or you don't. If you don't we can have configOrFail(), if you do, we cannot have config(). Blurring the lines makes things difficult and unsecure by default.

Long:

What I am pointing it is that Twig can be used to separate concerns. I totally forgot about that until both of you said it should no nothing about its context.

And you are right, it should not. Configure can still hold sensitive information if it is not just used in one place (consumed).

It is a good precaution that cake core consumes things, but doesn't mean `config()` should be in /by default/. It is also unsafe behavior added into a stable release which can catch other devs by surprise.

**Comment by ADmad** [comment]
> So this PR technically already breaks that because you can access all config settings from here. But I'm still merging it because I see use cases.

@WyriHaximus You already broke the scoping boundary by adding `env` filter, I just pushed the convenience a bit further :smile:

On that note I am excusing myself from this discussion and gonna stop spamming this issue.

**Pull request merged**
