### PR TITLE
Update use of removed method.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Cool thanks, already had this on my list for later today after seeing the other build fail :+1:

**Comment by ADmad** [comment]
Do you want me to also update the code formatting the new coding standard we will be using for Cake 4.x?

**Comment by WyriHaximus** [comment]
That would be great :+1: . Are you using some form of automation for that? (Also don't mind the slow builds, just enabled automatic dependency updates for the 4.x branch.)

**Comment by ADmad** [comment]
`phpcbf` included with `phpcs` takes care of  fixing majority of the errors. I'll make a PR soon.

**Comment by WyriHaximus** [comment]
Awesome :+1:

**Pull request merged**
