### PR TITLE
Correct fallback order so all extensions are check before falling back to the next path on the list

### PR DESCRIPTION
**Pull request by WyriHaximus**
As reported by @ADmad the current behavior causes issue for `cakephp/bake`.

### CODE REVIEW

**Comment by ADmad** [comment]
Awesome, I'll try it out with bake and report back.

**Comment by ADmad** [comment]
It works :tada:

**Comment by inoas** [comment]
Will this make it into 5.x-branch as well?

**Comment by WyriHaximus** [comment]
@inoas yes!

**Comment by WyriHaximus** [comment]
@admad `4.2.1` has just been released with this fix

**Comment by ADmad** [comment]
Thank you for taking care of this so quickly.

**Pull request merged**
