### PR TITLE
Template exts: Prioritize .twig -> .tpl -> .ctp

### PR DESCRIPTION
**Pull request by inoas**

### CODE REVIEW

**Comment by inoas** [comment]
I don't know when I find time to setup a local dev env for Twig but this PR requires changes around the tests and possibly test comparison file names.

**Comment by WyriHaximus** [comment]
If you have *nix based system and you have both git and php installed on it you can clone your fork, checkout your branch and run `make` and that will install all composer dependencies and run the unit tests.

**Comment by inoas** [comment]
Didn't see the makefile. If you can't do the fixes yourself I will try to squeeze them in yourself.

TLDR:
Makefiles. That's awesome and makes me wonder why https://github.com/cakephp/app doesn't come with such things and - skimmed through https://github.com/cakephp/cakephp/blob/master/Makefile and it seems to do more/complex stuff.

**Comment by WyriHaximus** [comment]
Can do the changes, just not today. Currently at work, and booked in the evening.

Seems that it's mainly a matter of renaming files and update the tests where needed.

Yup makefiles are awesome, and I ship them in nearly all my projects these days :smile: . Mainly as easy use for me, but also to let contributors like you get started quickly.

**Comment by WyriHaximus** [comment]
Is there anyway I can assist with this? Want to see if I can get this out the door today :smile:

**Comment by inoas** [comment]
I'll be honest I cannot do soon (I am not even using Twig, just planning to and it looks awesome!).

I think just test cases have to be fixed.

**Comment by WyriHaximus** [comment]
Alright no problem, I'll look into it :+1:

**Comment by WyriHaximus** [comment]
FYI #39

**Pull request merged**
