### PR TITLE
Use initialize() instead of overriding constructor.

### PR DESCRIPTION
**Pull request by ADmad**
Override loadHelper() and get rid of generateHelperList().

### CODE REVIEW

**Comment by ADmad** [comment]
This would require bumping at least minor version I guess.

**Comment by ADmad** [comment]
Using `initialize()` allows one to register listener for construct event in my `AppView::initialize()`. Currently the event gets dispatch in constructor itself before the listener is registered.

**Comment by inoas** [comment]
> This might require bumping at least minor version I guess.

Master currently targets PHP 7.0 / potentially Twig 5.0.0 I think. So that would be a non-issue.
However if you want to use < PHP 7.0 / Twig ^1.0 then this PR must also go against https://github.com/WyriHaximus/TwigView/tree/4.x

**Comment by ADmad** [comment]
I would like to have this fixed sooner rather than later,  so yes targeting 4.x would be better. Will just wait for@WyriHaximus' feedback though.

**Comment by WyriHaximus** [comment]
Test failure are unrelated and fixed in master. Thank for your work @ADmad looks great and makes sense :+1: . About `4.x`, do you want to PR the changes there or should I do them?

**Comment by inoas** [comment]
How will this find it's way into 4.x?

**Comment by ADmad** [comment]
@WyriHaximus I'll take care of 4.x too.

**Pull request merged**
