### PR TITLE
subcompile() expects \Twig_NodeInterface

### PR DESCRIPTION
**Pull request by edggids**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Awesome thanks :+1:

**Comment by inoas** [comment]
Thanks for caring!

**Comment by WyriHaximus** [comment]
Will tag this into a release later today

**Comment by edggids** [comment]
Thanks

**Comment by WyriHaximus** [comment]
[`4.0.3`](https://github.com/WyriHaximus/TwigView/releases/tag/4.0.3) has been tagged with this fix in it.

**Pull request merged**
